### ISSUE TITLE
what is days? 

### ISSUE THREAD

**Issue by bfid111** [CMPSC221/Schedule-Application#2]
private boolean[] days = new boolean[7];
 in Meeting class 
So I'm guessing this tells if certain days of the week has a schedule or not. 
Am I correct? 
if days[0] is false, it means there are is no schedule on Monday?

**Comment by RobertBColton** [comment]
Yes, that was my interpretation of the project overview.

> Meeting Information – represents a single meeting of a section
> Days
> Start time
> Stop time

I originally had ArrayList<DayOfWeek> but the DayOfWeek enum was just added in Java 8 and although this is a new project I didn't feel right using anything too new. The other thing is that it could be problematic as you could add more than 7 days of the week to ArrayList unless we kept it private.

So when days[x] is true it means that the Meeting occurs on that day of the week. Does that sound good?

**Comment by bfid111** [comment]
Everything sounds good. So we are assuming that Monday is days[0] and so on?

**Comment by RobertBColton** [comment]
We could, and we could also use DayOfWeek.MONDAY for example to index the array. But again, I am not sure about doing that, specifically because the Oracle docs say not to use the numeric value because they could randomly change the values if they wanted to (even if they likely never will). We could also just create our own DayOfWeek enum.

Another thing is the length of the array... I know this sounds crazy, nobody will ever change the number of days in a week, but we **could** replace 7 with DayOfWeek.values().length just to be **technically** correct.

And one other possibility is Map of DayOfWeek and boolean. Which is better than ArrayList because nobody could add more than the number of enum constants in DayOfWeek and if they did, it would be an error.

I am not sure which will be the best way to handle it until we start working on the project more, but we have the following possibilities:
```Java
Map<DayOfWeek, boolean> days;
boolean[] days = new boolean[DayOfWeek.values().length];
```

**Comment by bfid111** [comment]
`Map<DayOfWeek, boolean> days;`
looks ideal to me. but as you said, we are just starting with the project and we can always change it later if needed.

**Comment by RobertBColton** [comment]
Exactly, we just go with what works, is efficient, least likely to break, and takes the least code.

While we are on the subject, what Java version do you have? I am on the latest:

> Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Owner>java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

C:\Users\Owner>

**Comment by bfid111** [comment]
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Asus>java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

C:\Users\Asus>

Not the latest version but I'm willing to update if I need to .

**Comment by RobertBColton** [comment]
That will be fine, the professor probably has Java 7 too so we should target that. But that leaves out using DayOfWeek since it's Java 8, which I'm fine with.

So for the rules I guess, do we each just want to do one of the rules or should you guys do that since I outlined these other classes? I can do the InstructorConflict one at least because it seems the simplest. I was actually curious to read about the genetic algorithms though, because I am slightly familiar with the concept.

**Comment by bfid111** [comment]
InstructorConflict is checking if an instructor has two classes scheduled at the same time right? Since you outline these classes, I'll do instructorconflict and the part that checks if the schedule is a back to back schedule. Also, I think the Professor just guessed a random number that. Kinda funny number though haha.

**Comment by RobertBColton** [comment]
Sounds good I have to switch over to working on Calculus for a bit now. Tomorrow I have more Calculus to do too and Monday I'll be completely free.

Two other comments I want to make:

* I forgot that I wanted to add \@Override to the subclasses of Rule, so could you please do that? It helps prevent logic errors as the book mentions, then when we compile we can be sure that it actually overrides the parent method.

* Do you have preference for Swing or JavaFX? Since the class schedule has us read the Swing chapter I assume that the professor prefers we use it. Mainly because JavaFX is pretty new and we might run into something we need that doesn't exist yet. For example, I actually wrote the first docking control library for JavaFX https://github.com/RobertBColton/DockFX as a personal project.

That said, JavaFX makes data binding SUPER easy, as does the .NET Framework with C#. For example, all of the JavaFX classes use BooleanProperty and other Property beans. This means you can do cool things like checkBox.checkedProperty.bindBidirectional(checkBox2) so that when the user clicks one checkbox it automatically checks the other one. Now the reason this is important is because it is SUPER simple to bind JavaFX controls to databases http://blog.ngopal.com.np/2011/10/19/dyanmic-tableview-data-from-database/

With Swing this takes a lot more boilerplate. Do you think I should ask the professor if we can use JavaFX?

**Comment by bfid111** [comment]
I'm used to Swing using Netbeans and I've never used JavaFX before. But I don't mind using JavaFX and if JavaFX is better, I'm open to learning how to use it. So Yeah, you should ask Prof for permission.
