### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by bfid111** [CMPSC221/Schedule-Application#4]
I want to try adding new Schedule to Schedule Object but I can't figure out how to.
It seems like I'm supposed to create a Schedule object and use addSection to add new a schedule?
I'm kinda lost here. 
Also, I've created a method that checks if there is any conflicting schedule by comparing the start and end times but so far I've managed to make it work only by comparing the hours.
I think we need to use Calendar class to get precise with AM, PM and minutes.

**Comment by RobertBColton** [comment]
Sorry about that, my Calc. homework kept me busy for a few hours. 

I didn't go further on that one because I was unsure of a few things. We could just make a getSections() that returns the map and then you can add and remove as you like. However, then it would be possible to erroneously schedule two sections at the same time.

Using addSection we can first check the invariant/rule to make sure that we do not already have another section for the schedule that occurs at the same time. If we make a getSections() then everywhere else in the code that you modify it, you will have to check the Rule/invariant. As the book mentions, we want to sort of encapsulate that behavior so using addSection is kind of a better solution as far as the book is concerned. I mean similar to the same reasons that we keep the member variables private, so users of the classes/code don't go using them all willy nilly and then you go to change them and they break.

All of that considered, I think in our case it may be ok.
> Something that can rate a schedule with a non-negative value, 0 being defect free.
This quote from the project overview suggests that it is ok if the Schedule class temporarily has two sections scheduled at the same time. Which means it should be ok if we just remove addSection/removeSection and use getSections(). It's really hard to tell at this point, but I think we'd be safe to do that for now and then change it later if we need to.

The java.sql.Time class inherits from Date which has compareTo() so it actually has days already in it. Date values in Java, C++, and defined by RFCs are time in seconds since the last epoch, which occurred in 1970 I think.
https://docs.oracle.com/javase/7/docs/api/java/util/Date.html#compareTo%28java.util.Date%29

**Comment by bfid111** [comment]
So I created a method that checks if there is any conflict in the schedule (I'm not sure if it works, I need to test it but I wasn't able to create a schedule object properly.
I have no idea how to set up Schedule object so I will need your help setting up the testing environment.
and created a method that returns how many back-to-back classes are there in a schedule.

> Something that can rate a schedule with a non-negative value, 0 being defect free.

Basically, 0 means that the schedule is perfect
and I changed
`public int getFitness(Schedule schedule) ` in a way that it returns IMPOSSIBLE if the schedule is impossible and number of back-to-back classes * 10 ( 3 back to back = 30) if there is any back to back class in the schedule.

I guess we are good to go for this week's assignment and
we need to add 1 more rule in Rule class.
What would it be?

**Comment by RobertBColton** [comment]
I am actually not sure what you mean by testing environment. Are you referring to unit testing?

There is still one other thing we need to do yet, and that is the Instructor and Section id's.
Section number (unique id - autogenerated)
Id (unique id – user assigned)

The reason I left Instructor id be passed in the constructor and then added the setId mutator was so that the user could assign. Now since section number is autogenerated I think we would want it to be final. Also I was unsure which of these two or both should be SQL like primary keys. I believe the convention in Java is to use the UUID type which I was going to write but was not sure about. It's hard to tell if that will work for us when we get to using SQL or if we will need SQL to generate our primary keys for us.
http://www.javapractices.com/topic/TopicAction.do?Id=56http://www.javapractices.com/topic/TopicAction.do?Id=56

Also, does he want us to have the genetic algorithm done by Monday? I am not sure because it's not explicitly listed with the deliverables. Maybe I should ask him about that too.
http://www.theprojectspot.com/tutorial-post/creating-a-genetic-algorithm-for-beginners/3

The project overview does say:

> The system will generate a workable schedule that attempts to meet a set of rules.

But it's not mentioned in the deliverables, he just emailed us about it.

**Comment by bfid111** [comment]
I was referring to unit testing, I think. Like I just want to see how to add new schedule to Schedules.
Oh, so it has to attempt to meet the rules not strictly have to. 
Okay, so what should I do with the instructor and section ids?

**Comment by LavenderM** [comment]
I am not sure if we need to add GUI application now.

In the overview:

Your application should allow for

Entering/Editing/Deleting of instructor information
Entering/Editing/Deleting of section information

So the instruction and section ids are assigned by the user, the application will allow the user to enter and edit these information.

**Comment by bfid111** [comment]
Okay, we have 2 rules mapped out so far. We need to add one more. Any ideas?

**Comment by RobertBColton** [comment]
First, please see #5 that I just merged.

For unit testing we would have to pick a preferred unit testing framework, like JUnit. We can do that but for our small project I wasn't sure if it would be necessary. So say we make an update in the future, we can verify that none of our Rule's break because we can run the unit tests to make sure they all pass before merging any changes. 

Either way, unit testing is good because you just write a few methods that verify a specific function works and doesn't break. Apparently GitHub has unit testing integration as well, so in the README.md area of the repo you get a little sticker that says "build|passing" which I just seen on https://github.com/mayah/tinytoml about a week ago.

However, I should tell you guys, I have never set up unit testing before on any of my projects, but the experience would be good for me. If we decide on that I think we should look at doing it after tomorrow as it may take us a few days before we get it all working. I'll look and gather more information tomorrow morning.

**Comment by RobertBColton** [comment]
@LavenderM I emailed the professor last night to ask if we can use JavaFX because of how easy it makes it to bind data to controls, such as binding a database to a TableView. I got his response earlier today:

> Robert,
> 
> Let me mull that over a bit.
> 
> -- Hal

So unless he responds by tomorrow I doubt that we need to do any GUI right now. Also, the course agenda does not tell us to read the GUI chapters until the week starting tomorrow (now today) Monday May 30th. So I think we're good on that for right now, we can start adding a GUI early though as it helps test out the data, but I'd wait till I get his response to do that.

**Comment by RobertBColton** [comment]
@bfid111 
> Oh, so it has to attempt to meet the rules not strictly have to. 

Yes, and also I think he wants us to make it auto generate randomly fit schedules too. So like the genetic algorithm I linked above we need a method that goes through and creates a few random schedules then "breeds" them throwing in a few "mutations" to get a perfect schedule.

If that seems a little challenging, I can handle that part since I did the reading on it already and I think I already know how to accomplish that.

Also regarding the Rule's I interpreted it to mean that checkConflicts and checkBackToBack would be two separate rules. Don't we also have to do two more Rule's, because SpecificRule just returns 0?

**Comment by bfid111** [comment]
@RobertBColton 
So the genetic algorithm that we implement should take a crappy schedule and change it in a way that it creates a better schedule? 
Yes, checkConflicts and checkBacktoBack are two separate rules.I moved checkBacktoBack out of InstructorConflict class just now. 
I will add one more rule. Maybe a rule that checks if the instructor exceeds certain amount of lecture hour in day.

**Comment by RobertBColton** [comment]
I've taken care of the id's for now in #6 the best way I can think of right now until we progress further on the project. In the end I think we'll end up having the SQL method auto generate the id and then pass that to the constructor. So I don't think when we finish the project that we'll still be using AtomicInteger, but I think that's good for now, agreed?

**Comment by RobertBColton** [comment]
@bfid111 I had another idea, we could make prerequisite courses for the third Rule. Also, we could pick any of the following that Penn State has on its own schedule restrictions just for some ideas:
https://handbook.psu.edu/content/schedule-planning

**Comment by RobertBColton** [comment]
And yes that is how I think this will all work in. The genetic algorithm will do that and use the Rule classes for testing out the fitness score. I guess it will just keep breeding the schedules with some mutations until the fitness score becomes 0?

**Comment by bfid111** [comment]
Hmmm, I've already made another rule that checks if the instructor teaches more than 40 hours a week  so we could turn in this week's assignment for now.  

> The basic idea is that there are a set of classes that need to be offered and a pool of available instructors. You will need to figure out a way (I'll give you more info on that in weeks to come) to create an optimal schedule based on a set of rules that we will evolve. For example, 

- one instructor can't teach two sections at the same time
- it is better for instructors to have at least one session between two classes than back-to-back sessions

and so on. Some rules will result in impossible situations (e.g., rule 1) whereas others are just less optimal (e.g., rule 2)

I don't get what you mean by prerequisite courses. Are you talking about students?

**Comment by RobertBColton** [comment]
Nope that's good, I was actually just suggesting a third rule since I thought you meant you didn't have idea for it. We're good on that.

**Comment by bfid111** [comment]
So should I turn it what we have now? Do you have anything to change?

**Comment by LavenderM** [comment]
I think we are fine now. In this week he just wants Java classes for the core entities of the system and three rules.

**Comment by RobertBColton** [comment]
Are we sure he doesn't want the genetic algorithm yet?

**Comment by bfid111** [comment]
Ok, I'll turn in what we have so far

**Comment by RobertBColton** [comment]
Sounds good.

**Comment by bfid111** [comment]
Anyone hear anything from the Professor?

**Comment by RobertBColton** [comment]
I've not heard anything from the professor yet either.

**Comment by bfid111** [comment]
Should we start with GUI?? I'm kinda scared that prof didn't send any message

**Comment by RobertBColton** [comment]
I am not sure, I too find it odd that he has not said anything. We should be starting on the next milestone and he hasn't entered any grades yet either. There's only two groups or a total of 5 people in the class?

**Comment by bfid111** [comment]
Theres only 5 people in the class and 2 groups. Yeah, its a small class

**Comment by RobertBColton** [comment]
Do you want to email him tomorrow/now today (Saturday) if we don't hear anything new?

**Comment by bfid111** [comment]
I emailed him like 5 hours ago, no answer. According to the agenda, it says

> GUI Components

I don't know what happened to him but this is frustrating

**Comment by bfid111** [comment]
Okay, i got an email that he posted a new assignment. But I can't access it.. wtf?

**Comment by RobertBColton** [comment]
I can't see it either... I got no notifications at all.
